apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dev
  labels:
    app: backend
    app: frontend
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: examplepassword
  POSTGRES_DB: sampledb
  SESSION_ENCRYPT_SECRET: 7EwNLyb6QQX7Mr0B
  SESSION_ALGORITHM: aes-192-cbc
  JWT_VERIFY_SECRET: L6xOeIB5b1X7CnkXGRpCvaAJvFbHvS3a
  JWT_VERIFY_EXPIRY: 1d
  JWT_SESSION_SECRET: uGXbqsLwLb4gsGcqgtFgcrT3TGRMjchZ
  JWT_SESSION_EXPIRY: 1d
