apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sanjoydeb0007/robendevs-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_VERSION
          value: "v1"
        - name: SESSION_ENCRYPT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SESSION_ENCRYPT_SECRET
        - name: SESSION_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SESSION_ALGORITHM
        - name: JWT_VERIFY_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_VERIFY_SECRET
        - name: JWT_VERIFY_EXPIRY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_VERIFY_EXPIRY
        - name: JWT_SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SESSION_SECRET
        - name: JWT_SESSION_EXPIRY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SESSION_EXPIRY
        - name: DB_HOST
          value: "postgres"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_DB
        - name: DB_PORT
          value: "5432"
