apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-cluster-simulator
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-cluster-simulator
  template:
    metadata:
      labels:
        app: db-cluster-simulator
    spec:
      containers:
      - name: db-cluster-simulator
        image: postgres:15-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "examplepassword"
        - name: DB_WRITE_URL
          value: "postgres://primary:5432/sampledb"
        - name: DB_READ_URL
          value: "postgres://replica:5432/sampledb"
        ports:
        - containerPort: 5432
