name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: [self-hosted, Windows, X64]
    env:
      REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      BACKEND_IMAGE: ${{ secrets.BACKEND_IMAGE }}
      FRONTEND_IMAGE: ${{ secrets.FRONTEND_IMAGE }}
      DOCKER_BUILDKIT: 0
    steps:
      - name: Use default Docker context
        run: docker context use default
        shell: pwsh
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./apiserver
          file: ./apiserver/Dockerfile.backend
          push: true
          tags: ${{ env.BACKEND_IMAGE }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile.frontend
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set Namespace
        id: set-namespace
        run: echo "namespace=dev" >> $GITHUB_OUTPUT

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -n ${{ steps.set-namespace.outputs.namespace }} -f k8s/Structure/
          kubectl apply -n ${{ steps.set-namespace.outputs.namespace }} -f k8s/Observability/