name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Gitleaks to check for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --exclude-paths "apiserver/example.env,k8s/Structure/app-secret.yaml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    needs: gitleaks-scan
    runs-on: [self-hosted, Linux, X64]
    env:
      REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      BACKEND_IMAGE: ${{ secrets.BACKEND_IMAGE }}
      FRONTEND_IMAGE: ${{ secrets.FRONTEND_IMAGE }}
      DOCKER_BUILDKIT: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./apiserver
          file: ./apiserver/Dockerfile.backend
          push: true
          tags: ${{ env.BACKEND_IMAGE }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile.frontend
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}


  trivy-scan:
    needs: build-and-push
    runs-on: [self-hosted, Linux, X64]
    env:
      BACKEND_IMAGE: ${{ secrets.BACKEND_IMAGE }}
      FRONTEND_IMAGE: ${{ secrets.FRONTEND_IMAGE }}
    steps:
      - name: Scan backend image for vulnerabilities (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.BACKEND_IMAGE }}

      - name: Scan frontend image for vulnerabilities (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.FRONTEND_IMAGE }}

  deploy:
    needs: trivy-scan
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set Namespace
        id: set-namespace
        run: echo "namespace=dev" >> $GITHUB_OUTPUT

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -n dev -f k8s/Structure/
          # kubectl apply -n dev -f k8s/Observability/  # <--- hidden